alias ls='ls --color'
alias t='todo.sh'
alias ec='emacsclient -nw'
alias xo='xdg-open'
alias nvim='emacsclient -nw'
alias vi='emacsclient -nw'
export EDITOR='emacsclient -t'
export VISUAL=$EDITOR
export ALTERNATE_EDITOR=''
